In [17]:
import numpy as np
from mpi4py import MPI

import pyccl
import healpy as hp
import numpy as np
import matplotlib.pyplot as plt
import math
import os
import time

import sys
sys.path.append("./simulation_code/")
from simulate_des_maps import *

os.environ["PATH"]='/home/ngrewal/flask/flask/bin:'+os.environ["PATH"] 

In [2]:
x = np.linspace(1,100,100)

def f(x):
    return x**2

In [3]:
f(x)

array([1.000e+00, 4.000e+00, 9.000e+00, 1.600e+01, 2.500e+01, 3.600e+01,
       4.900e+01, 6.400e+01, 8.100e+01, 1.000e+02, 1.210e+02, 1.440e+02,
       1.690e+02, 1.960e+02, 2.250e+02, 2.560e+02, 2.890e+02, 3.240e+02,
       3.610e+02, 4.000e+02, 4.410e+02, 4.840e+02, 5.290e+02, 5.760e+02,
       6.250e+02, 6.760e+02, 7.290e+02, 7.840e+02, 8.410e+02, 9.000e+02,
       9.610e+02, 1.024e+03, 1.089e+03, 1.156e+03, 1.225e+03, 1.296e+03,
       1.369e+03, 1.444e+03, 1.521e+03, 1.600e+03, 1.681e+03, 1.764e+03,
       1.849e+03, 1.936e+03, 2.025e+03, 2.116e+03, 2.209e+03, 2.304e+03,
       2.401e+03, 2.500e+03, 2.601e+03, 2.704e+03, 2.809e+03, 2.916e+03,
       3.025e+03, 3.136e+03, 3.249e+03, 3.364e+03, 3.481e+03, 3.600e+03,
       3.721e+03, 3.844e+03, 3.969e+03, 4.096e+03, 4.225e+03, 4.356e+03,
       4.489e+03, 4.624e+03, 4.761e+03, 4.900e+03, 5.041e+03, 5.184e+03,
       5.329e+03, 5.476e+03, 5.625e+03, 5.776e+03, 5.929e+03, 6.084e+03,
       6.241e+03, 6.400e+03, 6.561e+03, 6.724e+03, 

In [7]:
comm = MPI.COMM_WORLD
rank = comm.Get_rank()
print(rank)

0


In [25]:
omega_b = 0.048
omega_m = 0.3
h = 0.7
n_s = 0.96
sigma_8 = 0.8
b1 = 1.42
b2 = 1.65
b3 = 1.60
b4 = 1.92
b5 = 2.00
smoothing=20
nside=256


sim=2
c_maps= np.zeros((sim,5,12*nside**2))
l_maps = np.zeros((sim,4,12*nside**2))
for i in range(sim):
    c_maps[i],l_maps[i] = simulate_des_maps_bias(omega_b, omega_m, h, n_s, sigma_8, smoothing, nside, b1, b2, b3, b4, b5)

In [27]:
c_maps[0]

array([[ 2.53694807,  2.14923797,  1.84916363, ...,  4.10439071,
         4.83691896,  4.11703194],
       [ 3.33725321,  3.48307077,  3.27985238, ...,  6.16595428,
         8.33684544,  6.86836761],
       [ 8.43740292,  9.61560073, 10.97045113, ..., 11.71593026,
        12.71132229,  9.45098642],
       [ 3.9131057 ,  3.68060274,  4.4274911 , ...,  9.39276273,
         7.6924461 ,  7.9859407 ],
       [ 1.30621279,  0.96041564,  1.19037871, ...,  1.78216556,
         1.16879503,  1.37263461]])

In [11]:
np.zeros(100, dtype='i') + 1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [ ]:
# do in py files
# command makes copies and can communicate w each other

# 2 ways: mpi (each have own program, but slower, easier to debug) & threading (shared resources, faster, easier to mess up)
# can use hybrid of two
